    # Account endpoints

login:
    path: /login
    controller: App\Controller\AccountController::login
    methods: POST

getAccountDetails:
    path: /getAccountDetails
    controller: App\Controller\AccountController::getAccountDetails
    methods: POST

getAuthenticatedURL:
    path: /getAuthenticatedURL
    controller: App\Controller\AccountController::getAuthenticatedURL
    methods: POST

DRM:
    path: /DRM
    controller: App\Controller\AccountController::DRM
    methods: [POST, GET]


    # Order endpoints

updateOrders:
    path: /orders
    controller: App\Controller\OrderController::updateOrders
    methods: POST

getOrders:
    path: /getCustomerOrders
    controller: App\Controller\OrderController::getCustomerOrders
    methods: POST


    # Subscription endpoints

subscriptions:
    path: /subscriptions
    controller: App\Controller\SubscriptionController::updateSubscriptions
    methods: POST

deleteSubscriptions:
    path: /subscriptions/{subscriptionId}
    controller: App\Controller\SubscriptionController::deleteSubscription
    methods: DELETE

getSubscriptions:
    path: /getCustomerSubscriptions
    controller: App\Controller\SubscriptionController::getCustomerSubscriptions


    # Templates

loginPage:
    path:         /login.html
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: login.html
    methods: GET

accountTemplate:
    path:         /account/{accountId}/overview.html
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: account.html
    methods: GET

orderTemplate:
    path:         /account/{accountId}/order/{orderId}/overview.html
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: order.html
    methods: GET

subscriptionsTemplate:
    path:         /account/{accountId}/order/{orderId}/subscription/{subscriptionId}/overview.html
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: subscription.html
    methods: GET

